### ISSUE TITLE
Doesn't connect

### ISSUE THREAD

**Issue by marcarc** [kchurch981/Vitalsouce_PDF_Converter#2]
Hi, 
I don't really know what I'm doing wrong, may could help me...
Here is the command line error what I get:

ChromeDriver 85.0.4183.87 
Google Chrome 85.0.4183.102
Python selenium-3.141.0.

```
> Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license()" for more information.
> >>> 
> = RESTART: C:\Users\Marcello\Desktop\VitalSource_PDF_Converter-master\web_scraper.py
> VitalSource Webscraper...
> Please enter your desired webpage: https://bookshelf.vitalsource.com/#/books/###  ***BOOK ID *** /pageid/1
> Please enter your username: *************
> Please enter your password: **********
> Traceback (most recent call last):
>   File "C:\Users\Marcello\Desktop\VitalSource_PDF_Converter-master\web_scraper.py", line 101, in <module>
>     run = Scraper(webpage, username, password)
>   File "C:\Users\Marcello\Desktop\VitalSource_PDF_Converter-master\web_scraper.py", line 32, in __init__
>     self.driver = webdriver.Chrome(options=chrome_options)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
>     desired_capabilities=desired_capabilities)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81
```
I tried several option, to fix, but no results. 
I tried to use different URL links too.
Thank you :)

**Comment by kchurch981** [comment]
If you read the last line of the error you'll see `This version of ChromeDriver only supports Chrome version 81` If you are not using chrome version 81 you'll need to figure out what version of chrome you're using and then download the perspective chromedriver. You can look up chromedrivers here: https://chromedriver.chromium.org/downloads
And you can find your chrome version by selecting help and about

**Comment by marcarc** [comment]
Thank you!
Now working.
